### ISSUE TITLE
Need help with C++ function indexing query

### ISSUE THREAD

**Issue by jmataraz** [ubolonton/emacs-tree-sitter#31]
Experimenting with a drop in replacement for imenu indexing, per the other issue mentioning it. I'm not having much success getting a query capture back from the tools, and was hoping for some help.

Here's the query and command:
```
(defvar joe:func-query
  (ts-make-query (tree-sitter-require 'cpp) [(function_definition (identifier) @function)]))

(defun joe:make-index (capture)
  (pcase-let ((`[_ ,node] capture))
    (cons (ts-node-text node)
      (ts-node-start-position node))))

(defun tree-sitter-c++-imenu-index-function ()
  (thread-last
    (ts-root-node tree-sitter-tree)
    (ts-query-captures joe:func-query)
    (seq-map #'joe:make-index)))
```

Running tree-sitter-debug-enable in the C++ file generates a full top-down tree, with plenty of function_definition nodes.

If I run a call to eval expression with the contents
`
(ts-query-captures joe:func-query (ts-root-node tree-sitter-tree))
`
it comes back with an empty vector, "[]"

Suggestions for debugging?

**Comment by jmataraz** [comment]
FWIW, I tried running a similar query on query.rs that is part of this project:

M-x tree-sitter-mode
M-:  `(ts-query-captures (ts-make-query (tree-sitter-require 'rust) [(function_item (identifier) @function)]) (ts-root-node tree-sitter-tree))`

and this generated the expected vector of results. Something busted with the c/cpp grammar maybe?

**Comment by ubolonton** [comment]
The C++ grammar is different:

```
  function_definition: 
    primitive_type: 
    function_declarator: 
      scoped_identifier: 
        namespace_identifier: 
        identifier: 
      parameter_list: 
        parameter_declaration: 
          primitive_type: 
          identifier: 
        parameter_declaration: 
          primitive_type: 
          identifier: 
        parameter_declaration: 
          primitive_type: 
          identifier: 
```

This query works:

```scheme
[(function_definition
  (function_declarator
   (scoped_identifier) @function))]
```

Also, if you are using the latest version, captures are now cons cells, not vectors.
