### ISSUE TITLE
[javascript] Paint shorthand_property_identifier same color as property_identifier

### ISSUE THREAD

**Issue by danielpza** [ubolonton/emacs-tree-sitter#90]
Is it possible/appropriate to draw `shorthand_property_identifier` the same color as `property_identifier` in javascript. They are both used for property identifiers. For example:

```js
const foo = "hello world"

const config = {
	foo,
	bar: "baz",
};
```

which is equivalent to:

```js
const foo = "hello world"

const config = {
	foo: foo, // or foo: "hello world",
	bar: "baz",
};
```

I would expect `foo` and `bar` to be the same color, but they are not, `foo` doesn't have any specific color in this case:

![image](https://user-images.githubusercontent.com/17787042/103551391-470cdf00-4e78-11eb-8f35-1d474f94a030.png)

tree-sitter-debug-mode:
```
program:
  lexical_declaration:
    variable_declarator:
      identifier:
      string:
  lexical_declaration:
    variable_declarator:
      identifier:
      object:
        shorthand_property_identifier:
        pair:
          property_identifier:
          string:
```
