### ISSUE TITLE
highlight incorrectly and no way to customize

### ISSUE THREAD

**Issue by jcs090218** [ubolonton/emacs-tree-sitter#93]
![Image 4](https://user-images.githubusercontent.com/8685505/103613260-31271900-4f61-11eb-9dcf-d7799d187e35.png)

#### Issue 1

I have above c code and you may notice parameter `self` suppose to be highlighted the same as the first `self` that passed in as an argument. 

#### Issue 2

Then I tried to figure out what face that maybe I could customize myself but `self` in L13 does not have any face applied but `self` in L14 does have face `tree-sitter-hl-face:variable.parameter` to customize.

* `self` in L13 - `tree-sitter-hl-face:variable.parameter`
* `self` in L14 - none

---

#### Expected Behaviour

The above code is from this video, ["Tree-sitter - a new parsing system for programming tools" by Max Brunsfeld](https://www.youtube.com/watch?v=Jes3bD6P0To&ab_channel=StrangeLoop). Then drag the timeline to [9:38]() you should able to see the expected result.

**Comment by sogaiu** [comment]
I think this is a direct link to the spot in question: https://youtu.be/Jes3bD6P0To?t=578

**Comment by sogaiu** [comment]
![tree-sitter-strange-loop-talk-9_38](https://user-images.githubusercontent.com/33044872/103614992-1d81af80-4f6d-11eb-892a-a2dfeead672b.png)

I think the code in question is at the bottom of the image.

**Comment by jcs090218** [comment]
![Image 5](https://user-images.githubusercontent.com/8685505/103615228-2bcbcd80-4f65-11eb-9ce8-3291136a1f72.png)

I don't think this is relevant but Visual Studio gives me expected result.

**Comment by sogaiu** [comment]
![emacs-tree-sitter-javascript](https://user-images.githubusercontent.com/33044872/103616519-f082cc00-4f6f-11eb-8885-84c234c71c94.png)

FWIW, this is what I get in my emacs ATM.

**Comment by sogaiu** [comment]
![emacs-tree-sitter-c](https://user-images.githubusercontent.com/33044872/103616879-96363b00-4f70-11eb-9f64-1017d96c386e.png)

This is what I get ATM in my emacs.

**Comment by sogaiu** [comment]
As an additional tidbit, this is what I get via `tree-sitter-debug-mode`:
```
translation_unit: 
  function_definition: 
    type_identifier: 
    pointer_declarator: 
      function_declarator: 
        identifier: 
        parameter_list: 
          parameter_declaration: 
            type_identifier: 
            pointer_declarator: 
              identifier: 
    compound_statement: 
      return_statement: 
        field_expression: 
          identifier: 
          field_identifier: 
```
